<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Author' => $baseDir . '/abstraction/loc_royalties/Author.php',
    'AuthorQuery' => $baseDir . '/abstraction/loc_royalties/AuthorQuery.php',
    'Base\\Author' => $baseDir . '/abstraction/loc_royalties/Base/Author.php',
    'Base\\AuthorQuery' => $baseDir . '/abstraction/loc_royalties/Base/AuthorQuery.php',
    'Base\\Book' => $baseDir . '/abstraction/loc_royalties/Base/Book.php',
    'Base\\BookQuery' => $baseDir . '/abstraction/loc_royalties/Base/BookQuery.php',
    'Base\\Publisher' => $baseDir . '/abstraction/loc_royalties/Base/Publisher.php',
    'Base\\PublisherQuery' => $baseDir . '/abstraction/loc_royalties/Base/PublisherQuery.php',
    'Book' => $baseDir . '/abstraction/loc_royalties/Book.php',
    'BookQuery' => $baseDir . '/abstraction/loc_royalties/BookQuery.php',
    'Map\\AuthorTableMap' => $baseDir . '/abstraction/loc_royalties/Map/AuthorTableMap.php',
    'Map\\BookTableMap' => $baseDir . '/abstraction/loc_royalties/Map/BookTableMap.php',
    'Map\\PublisherTableMap' => $baseDir . '/abstraction/loc_royalties/Map/PublisherTableMap.php',
    'Publisher' => $baseDir . '/abstraction/loc_royalties/Publisher.php',
    'PublisherQuery' => $baseDir . '/abstraction/loc_royalties/PublisherQuery.php',
);
